apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP_NAME}-sa
  namespace: ${APP_NAME}
  annotations:
    iam.gke.io/gcp-service-account: ${APP_NAME}-sa@${GCP_PROJECT_ID}.iam.gserviceaccount.com
