apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ${APP_NAME}-ae-pipeline
spec:
  description: Agent Engine delivery pipeline for ${APP_NAME}
  serialPipeline:
    stages:
      - targetId: ${APP_NAME}-ae-dev
      - targetId: ${APP_NAME}-ae-qa
      - targetId: ${APP_NAME}-ae-prod
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: ${APP_NAME}-ae-dev
spec:
  customTarget:
    customTargetType: agent-engine
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: ${APP_NAME}-ae-qa
spec:
  requireApproval: true
  customTarget:
    customTargetType: agent-engine
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: ${APP_NAME}-ae-prod
spec:
  requireApproval: true
  customTarget:
    customTargetType: agent-engine
